import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import grid from "@/../public/grid/SL-072622-51930-14.jpg";
import NavbarDemo from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarDemo/>
        {children}
      </body>
    </html>
  );
}
